/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const actionInput: typeof import('./src/globals/index')['actionInput']
  const actionOutput: typeof import('./src/globals/index')['actionOutput']
  const actionState: typeof import('./src/globals/index')['actionState']
  const cache: typeof import('./src/globals/index')['cache']
  const core: typeof import('./src/globals/index')['core']
  const exec: typeof import('./src/globals/index')['exec']
  const fs: typeof import('./src/globals/index')['fs']
  const io: typeof import('./src/globals/index')['io']
  const path: typeof import('./src/globals/index')['path']
  const process: typeof import('./src/globals/index')['process']
}
