name: Release

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
    outputs:
      pr: ${{ steps.release.outputs.pr }}
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      sha: ${{ steps.release.outputs.sha }}

  pr-update-dist:
    name: PR Update Dist
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.pr }}
    env:
      PR_BRANCH: ${{ fromJSON(needs.release.outputs.pr).headBranchName }}
      PR_NUMBER: ${{ fromJSON(needs.release.outputs.pr).number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PR_BRANCH }}
          fetch-depth: 2

      - name: Setup Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Node Dependencies
        run: pnpm install

      - name: Bundle
        run: pnpm run bundle

      - name: Update PR
        # language="Shell Script"
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add ./dist
          git commit --amend --no-edit
          git push --force-with-lease

      - name: Reopen PR
        run: |
          gh pr close ${{ env.PR_NUMBER }}
          gh pr reopen ${{ env.PR_NUMBER }}
